function Mnemonicos(){}
	Mnemonicos.TAMANHO_PALAVRA = 16;
	Mnemonicos.TAMANHO_MEMORIA = 32768;
	Mnemonicos.LOAD = 48;
	Mnemonicos.STORE = 49;
	Mnemonicos.LOADIMED = 56;
	Mnemonicos.LOADINDEX = 60;
	Mnemonicos.STOREINDEX = 61;
	Mnemonicos.MOV=51;
	Mnemonicos.OUTCHAR=50;
	Mnemonicos.INCHAR = 53;
	Mnemonicos.ADD = 32;
	Mnemonicos.SUB = 33;
	Mnemonicos.MULT = 34;
	Mnemonicos.DIV = 35;
	Mnemonicos.INC = 36;
	Mnemonicos.LMOD = 37;
	Mnemonicos.LAND = 18;
	Mnemonicos.LOR = 19;
	Mnemonicos.LXOR = 20;
	Mnemonicos.LNOT = 21;
	Mnemonicos.SHIFT = 16;
	Mnemonicos.CMP = 22;
	Mnemonicos.JMP = 2;
	Mnemonicos.CALL = 3;
	Mnemonicos.RTS = 4;
	Mnemonicos.PUSH = 5;
	Mnemonicos.POP = 6;
	Mnemonicos.NOP = 0;
	Mnemonicos.HALT = 15;
	Mnemonicos.SETC = 8;
	Mnemonicos.BREAKP = 14;
	
	Mnemonicos.TAM = 5 ;      // Numero de instrucoes de duas linhas

	Mnemonicos.BLACK = 15;
	Mnemonicos.BROWN = 1;
	Mnemonicos.GREEN = 2;
	Mnemonicos.OLIVE = 3;
	Mnemonicos.NAVY = 4;
	Mnemonicos.PURPLE = 5;
	Mnemonicos.TEAL = 6;
	Mnemonicos.SILVER = 7;
	Mnemonicos.GRAY = 8;
	Mnemonicos.RED = 9;
	Mnemonicos.LIME = 10;
	Mnemonicos.YELLOW = 11;
	Mnemonicos.BLUE = 12;
	Mnemonicos.FUCHSIA = 13;
	Mnemonicos.AQUA = 14;
	Mnemonicos.WHITE = 0
